apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: xuyuwei19940909/manga-backend:v3
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service02
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
